language: cpp

sudo: required
dist: trusty

matrix:
  include:
    # - os: linux
    #   env:
    #     - SCRIPT=build-pi.sh

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - SCRIPT=build.sh
        - COMP=gcc-5
        - COMPXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - SCRIPT=build.sh
        - COMP=gcc-6
        - COMPXX=g++-6

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc5"
        - COMP=gcc-5
        - COMPXX=g++-5

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc6"
        - COMP=gcc-6
        - COMPXX=g++-6

before_install:
  - if [[ "${MATRIX_EVAL}" != "" ]]; then echo ${MATRIX_EVAL} && eval ${MATRIX_EVAL}; fi

script:
  # make sure CC and CXX is correctly set
  - if [[ "${COMP}" != "" ]]; then export CC=${COMP}; fi
  - if [[ "${COMPXX}" != "" ]]; then export CXX=${COMPXX}; fi
  - ${CXX} --version
  - sh ${SCRIPT}
