language: cpp

sudo: required
dist: xenial

matrix:
  include:
    - os: linux
      env:
        - SCRIPT=build-pi.sh

    - os: linux
      env:
        - SCRIPT=build-pi-new.sh

    - os: linux
      env:
        - SCRIPT=build.sh

script:
  - sh ${SCRIPT}
