language: cpp
sudo: required
dist: xenial
matrix:
  include:
  - os: linux
    env:
    - SCRIPT=build-pi.sh
  - os: linux
    env:
    - SCRIPT=build.sh
script:
- sh ${SCRIPT}
notifications:
  slack:
    secure: BvgWR9RwSciJ7EVL6fHqX5oQwU8nyB1WBpsOD+LVO5d07Ngr/jYepq2h61HJIv6A8yNCUii8qud74PqBAK8hosvfr5lpYGYvn7tWPEtI5j4YU8t88rWey2PYe+eFFDv0HlRKCd0MLr+kjlyK7FLUefFTZD8/G23nd86q74n5/Mo4cX3bJJwpwejIv+2Iuf+6agIfFHCS3J+I0VZ1GEO3H4+z9uRDKYlzED1dUcwLpY+HCecYc73FYcxMNlEIumiozynfru+AuczZ3yS1pYEc6Y1nkdvAeBtnfS10TpnilPCbDFq9K60Qu9+Hodr4k68XLQtt3Ph4wZO4fy0+RZbVYKxQOSasKhl+uMDFbVzN3d/ENNXN905KhP1ynRw3WnogCECpPvkSa2QOBJdX1FAqPLb2EYSYAhVwFvI3eDb1rFK9G3gXVCmnr7ccqBk327GVGldRoD23YWSf4aDprfq0V1wH0BxbBfI9ElKl7La9OGV8p1L7JnvYK01jZCFes8jIndcPM/2SiwG4wqLpcBP5i8TdpF1B40obia04fggHEZJ2AJRkDx5Tfj8sAF0TTN/hzatUbFaxauyTUaJ+m75x7N8Bb7WL39ACn4MXHRjgj5xh3NmpH7mch6uvJUIpzrvv4kb7+wVg+W2iFeF/zKcmIyAMOf5o8PKIu8ybvFd+Jjg=
