language: cpp

sudo: required
dist: xenial

matrix:
  include:
    - os: linux
      env:
        - SCRIPT=build-pi.sh

    - os: linux
      env:
        - SCRIPT=build-pi-new.sh

    - os: linux
      env:
        - SCRIPT=build.sh


before_install:
  - if [[ "${MATRIX_EVAL}" != "" ]]; then echo ${MATRIX_EVAL} && eval ${MATRIX_EVAL}; fi

script:
  # make sure CC and CXX is correctly set
  - if [[ "${COMP}" != "" ]]; then export CC=${COMP}; fi
  - if [[ "${COMPXX}" != "" ]]; then export CXX=${COMPXX}; fi
  - ${CXX} --version
  - sh ${SCRIPT}
