%YAML:1.0
---
# index de la camera
cameraIndex: 0

# résolution des photos brutes (NE PAS CHANGER, ou le driver video crash)
cameraResolution: [ 2592, 1944 ]

# procède à une conversion RGB -> BGR après lecture depuis la caméra
swapRgb: true

# taille réelle de la table en millimètres
boardSize: [ 3000, 2000 ]

# ratio à appliquer à la taille réelle pour créer l'image de travail
boardRatio: 0.5

# offset vertical a appliquer aux objets détectés (prendre en compte boardRatio)
yCorrection: 15

# diamètre réel des objets à détecter en millimètres
diametreObjet: 76

# largeur des sondes de culeur en pixels
probeSize: 20

# position des marqueurs (coin supérieur gauche) par identifiant ARUCO
markersPos:
   - [ 150, 150 ]
   - [ 380, 210 ]
   - [ 0, 0 ] # unused
   - [ 0, 0 ]
   - [ 750, 0 ]
   - [ 600, 150 ]

# position des pallets connus
blueRefs:
  - [ 170, 80 ]

greenRefs:
  - [ 280, 240 ]

redRefs:
  - [ 170, 80 ]

# listes des zones dans lequelles il peut y avoir des objets
detectZones:
  - [ 410, 100, 410, 300 ]
