%YAML:1.0
---
# index de la camera
cameraIndex: 0

# résolution des photos brutes
cameraResolution: [ 1280, 960 ]

# la camera est une fisheye (> 160°)
fisheye: 1

# procède à une conversion RGB -> BGR après lecture depuis la caméra
swapRgb: 0

# annule la distortion optique
undistort: 1

# largeur des sondes de couleur en pixels
probeSize: 15

# Délai entre chaque prise de photo
idleDelay: 1000

# Délai entre chaque détection
detectionDelay: 500

# Distance en pixels pour le clustering
seuilCluster: 100

# Zone de détection des échantillons (coordonnées table)
detectionZone: [450, 100, 2100, 1650]

# Zone de détection des distributeurs (coordonnées table)
detectionZone2: [1250, 0, 500, 100]
