%YAML:1.0
---
# index de la camera
cameraIndex: 0

# résolution des photos brutes
cameraResolution: [ 1280, 960 ]

# la camera est une fishete (> 160°)
fisheye: 1

# procède à une conversion RGB -> BGR après lecture depuis la caméra
swapRgb: 0

# annule la distortion optique
undistort: 1

# largeur des sondes de couleur en pixels
probeSize: 20

# Seuil de détection de couleurs
colorThreshold: 8

# Nombre de valeurs de détection pour moyenner
detectionBuffer: 4

# Nombre de valeurs identiques minimum pour valider la détection
detectionValidLimit: 3

# Délai entre chaque prise de photo
idleDelay: 1000

# Délai entre chaque détection
detectionDelay: 500
